---
title: "Homework 4"
author: "Katie Miller"
date: "`r Sys.Date()`"
output: word_document
message: FALSE
---
# Set Up

```{r download-packages}
# loading in the necessary packages
library(tidyverse)
library(here)
library(naniar)
library(dplyr)
```

```{r read-in-data}
# reading in the data using here package
fish <- read_csv(here("data", "ntl6_v12.csv"))
```

```{r filter-data}
# filtering data frame to extract relevant info
trout <- fish %>% 
  filter(spname %in% "TROUTPERCH") %>% 
  reframe(year = case_when(spname == "TROUTPERCH" ~ year4),
          species = case_when(spname == "TROUTPERCH" ~ spname),
          length = case_when(spname == "TROUTPERCH" ~ length),
          weight = case_when(spname == "TROUTPERCH" ~ weight)) 

```
# Problem 1

## 1
Null:
Alternative:

## 2
```{r visualize-missing-data}
gg_miss_var(trout) %>% 
  theme(plot.caption = "Plot 1. Missing weights of perch trout")
```
 
```{r}
trout_model <- lm(weight ~ length, data = trout)
```

```{r}
par(mfrow = c(2, 2))
plot(trout_model)
```

```{r}
dev.off()
```

```{r}
model_summary <- summary(trout_model)

model_summary
```

```{r}
model_squares <- anova(trout_model)

model_squares
```


